'use client';

import JSZip from 'jszip';
import { useEffect, useMemo, useState, type ChangeEvent } from 'react';
import { api, ApiError, ApiJob, waitForJob } from '../lib/api';

type Step = 'home' | 'sources' | 'analyzing' | 'brand' | 'brief' | 'strategy' | 'ideas' | 'content' | 'production' | 'creatives' | 'result';
type Idea = { id: string; ordinal: number; title: string; pillar: string; format: string; description: string; selected: boolean };
type Draft = { id: string; headline: string; caption: string; visual: string; approved: boolean; versions: string[] };
type Creative = { id: string; headline: string; approved: boolean; versions: number[]; color: string };

const ideaSeeds = [
  ['Seguro é diferente de proteção', 'Educação', 'Carrossel'], ['Quanto custa ficar sem seguro?', 'Conversão', 'Post único'], ['5 erros ao contratar um seguro', 'Educação', 'Carrossel'], ['Você protege o que realmente importa?', 'Engajamento', 'Post único'], ['Seguro residencial: vale a pena?', 'Educação', 'Carrossel'], ['Consórcio: por que escolher agosto?', 'Oportunidade', 'Post único'], ['O que seu seguro auto cobre de verdade?', 'Educação', 'Carrossel'], ['Proteção que cabe no seu plano', 'Conversão', 'Post único'], ['A casa muda. A proteção também.', 'Autoridade', 'Post único'], ['Seguro de vida é cuidado presente', 'Emocional', 'Post único'], ['Antes de assinar, faça estas perguntas', 'Educação', 'Carrossel'], ['Seu carro merece mais tranquilidade', 'Emocional', 'Post único'], ['Consórcio sem complicação', 'Educação', 'Carrossel'], ['Checklist de proteção familiar', 'Educação', 'Carrossel'], ['Por que revisar sua apólice?', 'Autoridade', 'Post único'], ['Proteção para cada nova fase', 'Emocional', 'Post único'], ['Mitos sobre seguro residencial', 'Educação', 'Carrossel'], ['Planeje hoje, conquiste amanhã', 'Oportunidade', 'Post único'], ['A escolha que protege seu patrimônio', 'Autoridade', 'Post único'], ['Seguro não é gasto. É estratégia.', 'Conversão', 'Post único'], ['Quem cuida, se antecipa', 'Emocional', 'Post único'], ['Três coberturas que fazem diferença', 'Educação', 'Carrossel'], ['Sua empresa também precisa de proteção', 'Autoridade', 'Post único'], ['Consórcio para tirar planos do papel', 'Oportunidade', 'Carrossel'], ['Sinais de que é hora de revisar', 'Educação', 'Post único'], ['Tranquilidade tem nome: planejamento', 'Emocional', 'Post único'], ['Proteja seu futuro em 3 passos', 'Conversão', 'Carrossel'], ['O seguro ideal começa por ouvir você', 'Autoridade', 'Post único'], ['Mais clareza nas suas escolhas', 'Educação', 'Post único'], ['Agosto é um bom mês para planejar', 'Oportunidade', 'Post único']
];
const colors = ['#082b55', '#123f74', '#f25b35', '#12304b', '#1d5ca0', '#eb6a36', '#1b4369', '#082039', '#d95032', '#386798', '#0c315b', '#ef5e33'];

function loadProjects() { try { return JSON.parse(localStorage.getItem('red-ai-projects') || '[]') as { name: string; campaign: string; step: Step }[]; } catch { return []; } }
function Field({ label, value, onChange, optional, area = false }: { label: string; value: string; onChange: (v: string) => void; optional?: boolean; area?: boolean }) { const p = { value, onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => onChange(e.target.value), placeholder: label }; return <label className="field"><span>{label}{optional && <i> opcional</i>}</span>{area ? <textarea {...p} rows={4} /> : <input {...p} />}</label>; }
function Button({ children, onClick, disabled, secondary = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean; secondary?: boolean }) { return <button className={secondary ? 'button secondary' : 'button'} disabled={disabled} onClick={onClick}>{children}</button>; }

export default function App() {
  const [step, setStep] = useState<Step>('home'); const [brand, setBrand] = useState('Cassel Seguros'); const [instagram, setInstagram] = useState('@casselseguros'); const [website, setWebsite] = useState('https://www.casselseguros.com.br'); const [context, setContext] = useState('Corretora de seguros com foco em proteção de famílias e empresas.');
  const [campaign, setCampaign] = useState('Agosto — Proteção e Consórcio'); const [brief, setBrief] = useState('Aproveitar o período de agosto para reforçar a importância do planejamento e da proteção.'); const [ideas, setIdeas] = useState<Idea[]>([]); const [drafts, setDrafts] = useState<Draft[]>([]); const [creatives, setCreatives] = useState<Creative[]>([]); const [projects, setProjects] = useState<{ name: string; campaign: string; step: Step }[]>([]); const [activeDraft, setActiveDraft] = useState(0); const [activeCreative, setActiveCreative] = useState(0); const [revision, setRevision] = useState(''); const [installPrompt, setInstallPrompt] = useState(false);
  const [projectId, setProjectId] = useState<string>(); const [campaignId, setCampaignId] = useState<string>(); const [job, setJob] = useState<ApiJob>(); const [error, setError] = useState<string>(); const [retry, setRetry] = useState<(() => void)>(); const [sourceFiles, setSourceFiles] = useState<File[]>([]);
  useEffect(() => { setProjects(loadProjects()); if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined); const handler = (e: Event) => { e.preventDefault(); setInstallPrompt(true); }; window.addEventListener('beforeinstallprompt', handler); return () => window.removeEventListener('beforeinstallprompt', handler); }, []);
  const selected = useMemo(() => ideas.filter(i => i.selected), [ideas]); const approvedDrafts = drafts.filter(d => d.approved).length;
  function save(next: Step) { const entry = { name: brand || 'Nova marca', campaign: campaign || 'Campanha sem nome', step: next }; const rest = loadProjects().filter(p => p.name !== entry.name); const list = [entry, ...rest].slice(0, 5); localStorage.setItem('red-ai-projects', JSON.stringify(list)); setProjects(list); }
  function start() { setError(undefined); setProjectId(undefined); setCampaignId(undefined); setSourceFiles([]); setStep('sources'); }
  function selectSourceFiles(event: ChangeEvent<HTMLInputElement>) { const incoming = Array.from(event.target.files ?? []); setSourceFiles(existing => { const keys = new Set(existing.map(file => `${file.name}:${file.size}:${file.lastModified}`)); return [...existing, ...incoming.filter(file => !keys.has(`${file.name}:${file.size}:${file.lastModified}`))]; }); event.target.value = ''; }
  function removeSourceFile(index: number) { setSourceFiles(files => files.filter((_, fileIndex) => fileIndex !== index)); }
  function run(action: () => Promise<void>) { setError(undefined); setRetry(() => () => { void run(action); }); void action().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Ocorreu um erro inesperado.')); }
  async function beginAnalysis() { save('analyzing'); setStep('analyzing'); const project = await api.createProject({ name: brand, instagramHandle: instagram || undefined, websiteUrl: website || undefined, manualContext: context || undefined }); setProjectId(project.id); if (sourceFiles.length) await api.uploadSources(project.id, sourceFiles); const analysis = await api.analyzeBrand(project.id); await waitForJob(analysis, setJob); setStep('brand'); }
  async function generateIdeas() { if (!projectId) throw new ApiError('Projeto não encontrado. Reinicie a análise.'); await api.approveBrand(projectId); const nextCampaign = campaignId ? { id: campaignId } : await api.createCampaign(projectId, { name: campaign, objective: 'A IA decide a melhor estratégia', targetCount: 12, context: brief }); setCampaignId(nextCampaign.id); const strategy = await api.generateStrategy(nextCampaign.id); await waitForJob(strategy, setJob); await api.approveStrategy(nextCampaign.id); const generated = await api.generateIdeas(nextCampaign.id); await waitForJob(generated, setJob); const apiIdeas = await api.ideas(nextCampaign.id); setIdeas(apiIdeas.map((idea) => ({ id: idea.id, ordinal: idea.ordinal, title: idea.title, pillar: idea.pillar, format: idea.contentType, description: idea.description, selected: idea.selected }))); setStep('ideas'); }
  async function generateDrafts() { if (!campaignId) throw new ApiError('Campanha não encontrada.'); const approvedIdeas = await api.selectIdeas(campaignId, selected.map(idea => idea.id)); setIdeas(all => all.map(idea => ({ ...idea, selected: approvedIdeas.some(x => x.id === idea.id) }))); const generation = await api.generateContent(campaignId); await waitForJob(generation, setJob); const content = await api.content(campaignId); setDrafts(content.map(item => ({ id: item.id, headline: item.headline, caption: item.caption, visual: item.visualDirection ?? 'Fotografia humana, composição editorial e contraste azul profundo.', approved: false, versions: [`V${item.version}`] }))); setStep('content'); }
  function approveAllDrafts() { setDrafts(x => x.map(d => ({ ...d, approved: true }))); }
  async function reviseDraft() { if (!revision.trim() || !drafts[activeDraft]) return; const instruction = revision.trim(); const response = await api.reviseContent(drafts[activeDraft].id, instruction); setDrafts(items => items.map((d, i) => i === activeDraft ? { ...d, caption: `${d.caption} Ajuste solicitado: ${instruction}.`, versions: [...d.versions, `V${response.version}`] } : d)); setRevision(''); }
  async function produce() { if (!campaignId) throw new ApiError('Campanha não encontrada.'); setStep('production'); const generation = await api.generateCreatives(campaignId); await waitForJob(generation, setJob); setCreatives(drafts.map((d, i) => ({ id: d.id, headline: d.headline, approved: false, versions: [1], color: colors[i % colors.length] }))); setStep('creatives'); }
  async function reviseCreative() { if (!revision.trim() || !creatives[activeCreative]) return; const instruction = revision.trim(); const revisionJob = await api.reviseCreative(creatives[activeCreative].id, instruction); await waitForJob(revisionJob, setJob); setCreatives(items => items.map((c, i) => i === activeCreative ? { ...c, versions: [...c.versions, c.versions.length + 1] } : c)); setRevision(''); }
  async function exportZip() { if (projectId) { window.location.assign(api.exportUrl(projectId)); return; } const zip = new JSZip(); zip.file('captions.txt', drafts.map((d, i) => `${i + 1}. ${d.headline}\n${d.caption}\n`).join('\n')); const blob = await zip.generateAsync({ type: 'blob' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `${campaign.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-red-ai.zip`; a.click(); URL.revokeObjectURL(a.href); }
  const nav = (n: Step) => { save(n); setStep(n); };
  if (step === 'home') return <main className="home"><Header onProjects={() => undefined} install={installPrompt} /><section className="hero"><p className="eyebrow">CAMPANHAS QUE COMEÇAM COM CONTEXTO</p><h1>Transforme qualquer marca em uma campanha com IA.</h1><p>Da identidade ao resultado final. Com direção humana em cada escolha que importa.</p><Button onClick={start}>+ Nova análise</Button></section><section className="recent"><div className="section-title"><h2>Projetos recentes</h2><span>Modo mock ativo</span></div><div className="project-grid">{[{ name: 'Cassel Seguros', campaign: 'Agosto — Proteção e Consórcio', step: 'result' as Step }, { name: 'Redzone MKT', campaign: 'Posicionamento de marca', step: 'creatives' as Step }, ...projects].slice(0, 4).map((p, i) => <article className="project-card" key={`${p.name}-${i}`}><div className="project-mark">{p.name.slice(0, 2).toUpperCase()}</div><small>{p.step === 'result' ? 'CONCLUÍDO' : 'EM ANDAMENTO'}</small><h3>{p.name}</h3><p>{p.campaign}</p><button onClick={() => { setBrand(p.name); setCampaign(p.campaign); p.step === 'result' ? setStep('result') : start(); }}>Continuar <b>→</b></button></article>)}</div></section></main>;
  return <main><Header onProjects={() => setStep('home')} install={installPrompt} /><WizardProgress step={step} />{error && <div className="api-error" role="alert"><span>{error}</span><Button secondary onClick={() => retry?.()}>Tentar novamente</Button><button aria-label="Fechar erro" onClick={() => setError(undefined)}>×</button></div>}
    <section className="wizard">{step === 'sources' && <><StepTitle n="01" title="Fontes da Marca" text="Envie o contexto que ajuda a IA a entender sua marca." /><div className="form-grid"><Field label="Nome da marca" value={brand} onChange={setBrand} /><Field label="Instagram (@)" value={instagram} onChange={setInstagram} optional /><Field label="Site" value={website} onChange={setWebsite} optional /><Field label="Sobre a marca" value={context} onChange={setContext} optional area /></div><input id="brand-sources" className="file-input" type="file" multiple accept="image/png,image/jpeg,image/webp,application/pdf,image/svg+xml" onChange={selectSourceFiles} aria-describedby="brand-sources-help" /><label className="uploader" htmlFor="brand-sources"><span className="upload-icon" aria-hidden="true">⇧</span><strong>Clique para enviar materiais da marca</strong><span id="brand-sources-help">PNG, JPG, WEBP, PDF ou SVG. Você pode selecionar mais de uma vez.</span></label>{sourceFiles.length > 0 && <ul className="source-files" aria-label="Arquivos selecionados">{sourceFiles.map((file, index) => <li key={`${file.name}-${file.size}-${file.lastModified}`}><span>{file.name}</span><small>{Math.ceil(file.size / 1024)} KB</small><button type="button" onClick={() => removeSourceFile(index)} aria-label={`Remover ${file.name}`}>×</button></li>)}</ul>}<Footer next="✦ Mapear identidade" onNext={() => run(beginAnalysis)} /></>}
    {step === 'analyzing' && <><StepTitle n="02" title="Analisando a Marca" text="Nossa IA está analisando os materiais enviados." /><div className="analysis"><div className="ring"><strong>{job?.progress ?? 0}%</strong><span>{job?.message ?? 'Na fila'}</span></div><div className="checks">{['Lendo materiais enviados', 'Identificando cores e elementos visuais', 'Entendendo posicionamento e tom de voz', 'Analisando conteúdo e comunicação', 'Construindo Brand DNA'].map((x, i) => <p key={x} className={job && job.progress >= ((i + 1) * 20) ? 'done' : ''}>{job && job.progress >= ((i + 1) * 20) ? '✓' : '○'} {x}</p>)}</div></div></>}
    {step === 'brand' && <><StepTitle n="03" title="Brand DNA" text={`É assim que entendemos a ${brand}. Ajuste o que for necessário.`} /><div className="two-col"><div className="panel"><label>Paleta de cores</label><div className="palette">{['#062a54','#0a559b','#bdd3eb','#f4f4f2'].map(c => <i key={c} style={{ background: c }} />)}</div><Trait title="Personalidade" items={['Confiável','Humana','Clara','Tradicional','Acessível']} /><Trait title="Tom de voz" items={['Profissional','Educativo','Próximo']} /><Trait title="Público provável" items={['25–55 anos','Famílias','Empresários','Proprietários']} /></div><div className="panel"><label>Produtos e oportunidades</label><Trait title="Principais produtos" items={['Seguro Auto','Seguro Residencial','Seguro de Vida','Consórcio']} /><p className="detail">Fundos claros, uso predominante de azul, fotografias humanas, pouco ruído visual e comunicação instrucional.</p><Trait title="Evitar" items={['Alarmismo','Jargão técnico','Promessas absolutas']} /></div></div><Footer back={() => nav('sources')} next="Usar este Brand DNA →" onNext={() => nav('brief')} /></>}
    {step === 'brief' && <><StepTitle n="04" title="Planejando a Campanha" text="Vamos definir os objetivos e o contexto." /><div className="form-grid"><Field label="Nome da campanha" value={campaign} onChange={setCampaign} /><Field label="Objetivo" value="A IA decide a melhor estratégia" onChange={() => undefined} /><Field label="Quantidade final" value="12 conteúdos" onChange={() => undefined} /><Field label="Período" value="Agosto 2026" onChange={() => undefined} /><Field label="Contexto adicional" value={brief} onChange={setBrief} optional area /></div><Footer back={() => nav('brand')} next="✦ Planejar campanha" onNext={() => nav('strategy')} /></>}
    {step === 'strategy' && <><StepTitle n="05" title="Estratégia Proposta" text="Nossa estratégia para atingir o objetivo." /><div className="strategy"><div className="panel"><small>OBJETIVO DA CAMPANHA</small><h2>Construir autoridade em proteção patrimonial e transformar interesse em conversas.</h2><p>{brief}</p></div><div className="panel"><small>MIX DE CONTEÚDO</small>{[['Educação',35],['Autoridade',25],['Conversão',20],['Engajamento',10],['Institucional',10]].map(([x,n]) => <div className="mix" key={String(x)}><span>{x}</span><b>{n}%</b><i style={{ width: `${n}%` }} /></div>)}</div></div><Trait title="Pilares de conteúdo" items={['Proteção','Educação','Confiança','Oportunidade']} /><Footer back={() => nav('brief')} next="Aprovar estratégia →" onNext={() => run(generateIdeas)} /></>}
    {step === 'ideas' && <><StepTitle n="06" title="30 Ideias de Conteúdo" text="Selecione as 12 melhores ideias para a campanha." /><div className="selection"><b>Selecionadas: <em>{selected.length} / 12</em></b><span>{selected.length === 12 ? 'Seleção completa' : 'Escolha exatamente 12'}</span></div><div className="filters"><button>Todos</button><button>Educação</button><button>Autoridade</button><button>Conversão</button></div><div className="idea-list">{ideas.map(idea => <article className={`idea ${idea.selected ? 'selected' : ''}`} key={idea.id} onClick={() => setIdeas(all => { const count = all.filter(x => x.selected).length; return all.map(x => x.id === idea.id ? { ...x, selected: x.selected ? false : count < 12 } : x); })}><span>{String(idea.ordinal).padStart(2, '0')}</span><div><h3>{idea.title}</h3><p>{idea.description}</p><small>{idea.pillar} · {idea.format}</small></div><b>{idea.selected ? '✓' : '○'}</b></article>)}</div><Footer back={() => nav('strategy')} next="Continuar com 12 →" disabled={selected.length !== 12} onNext={() => run(generateDrafts)} /></>}
    {step === 'content' && <><StepTitle n="07" title="Conteúdo Proposto" text="Revise os textos antes de gerar as artes." /><div className="content-layout"><aside>{drafts.map((d, i) => <button className={i === activeDraft ? 'active' : ''} key={d.id} onClick={() => setActiveDraft(i)}><b>{String(i + 1).padStart(2, '0')}</b>{d.headline}<span>{d.approved ? '✓' : '○'}</span></button>)}</aside><DraftPanel draft={drafts[activeDraft]} revision={revision} setRevision={setRevision} onRevise={() => run(reviseDraft)} onApprove={() => setDrafts(a => a.map((d,i) => i === activeDraft ? { ...d, approved: true } : d))} /></div><div className="approval"><span>{approvedDrafts}/12 aprovados</span><Button onClick={approveAllDrafts} secondary>Aprovar todos</Button></div><Footer back={() => nav('ideas')} next="✦ Gerar artes" disabled={approvedDrafts !== 12} onNext={() => run(produce)} /></>}
    {step === 'production' && <><StepTitle n="08" title="Produzindo as Artes" text="Cada item é processado de forma independente." /><div className="production"><div className="ring"><strong>{job?.progress ?? 0}%</strong><span>{job?.message ?? 'Na fila'}</span></div>{['Copy ✓ 12/12','Direção criativa ✓ 12/12','Assets 9/12','Artes finais 7/12'].map(x => <p key={x}>✓ {x}</p>)}</div></>}
    {step === 'creatives' && <><StepTitle n="09" title="Revisão das Artes" text="Peça alterações quando algo não parecer natural." /><div className="creative-layout"><div className="creative-grid">{creatives.map((c,i) => <button className={`creative ${i === activeCreative ? 'active' : ''}`} style={{ background: c.color }} key={c.id} onClick={() => setActiveCreative(i)}><small>{String(i + 1).padStart(2,'0')}</small><strong>{c.headline}</strong><span>{c.approved ? '● Aprovado' : '○ Em revisão'}</span></button>)}</div><CreativePanel creative={creatives[activeCreative]} revision={revision} setRevision={setRevision} onRevise={() => run(reviseCreative)} onApprove={() => setCreatives(a => a.map((c,i) => i === activeCreative ? { ...c, approved: true } : c))} /></div><Footer back={() => nav('content')} next="Ver resultado final →" disabled={creatives.some(c => !c.approved)} onNext={() => nav('result')} /></>}
    {step === 'result' && <><div className="result-head"><p className="eyebrow">CAMPANHA FINALIZADA</p><h1>Campanha pronta.</h1><p>12 conteúdos com estratégia, copy e direção criativa alinhadas.</p><Button onClick={exportZip}>↓ Baixar campanha .ZIP</Button></div><div className="result-grid">{(creatives.length ? creatives : Array.from({length:12},(_,i) => ({id:i+1,headline:ideaSeeds[i][0] as string,color:colors[i],approved:true,versions:[1]}))).map(c => <article className="creative result-card" style={{background:c.color}} key={c.id}><small>{String(c.id).padStart(2,'0')}</small><strong>{c.headline}</strong><span>● Aprovado</span></article>)}</div><Footer back={() => nav('creatives')} next="Nova análise →" onNext={start} /></>}</section></main>;
}

function Header({ onProjects, install }: { onProjects: () => void; install: boolean }) { return <header><button className="logo" onClick={onProjects}>RED <b>AI</b></button><nav><span>AI_MODE: <b>MOCK</b></span>{install && <span className="install">Instalável</span>}<button onClick={onProjects}>Projetos</button></nav></header>; }
function WizardProgress({ step }: { step: Step }) { const steps: [string, Step[]][] = [['01 Marca',['sources','analyzing','brand']],['02 Estratégia',['brief','strategy']],['03 Ideias',['ideas']],['04 Conteúdo',['content']],['05 Artes',['production','creatives']],['06 Resultado',['result']]]; return <div className="progress">{steps.map(([name, mapped], i) => <span className={mapped.includes(step) ? 'now' : steps.slice(0,i).some(([,x]) => x.includes(step)) ? 'past' : ''} key={name}>{name}</span>)}</div>; }
function StepTitle({ n, title, text }: { n: string; title: string; text: string }) { return <div className="step-title"><span>{n}</span><div><h1>{title}</h1><p>{text}</p></div></div>; }
function Trait({ title, items }: { title: string; items: string[] }) { return <div className="trait"><label>{title}</label><div>{items.map(x => <button key={x}>{x}</button>)}</div></div>; }
function Footer({ back, next, onNext, disabled }: { back?: () => void; next: string; onNext: () => void; disabled?: boolean }) { return <footer>{back ? <Button secondary onClick={back}>← Voltar</Button> : <span />}<Button onClick={onNext} disabled={disabled}>{next}</Button></footer>; }
function DraftPanel({ draft, revision, setRevision, onRevise, onApprove }: { draft?: Draft; revision: string; setRevision: (v:string)=>void; onRevise:()=>void; onApprove:()=>void }) { if (!draft) return null; return <article className="draft-panel"><small>VERSÕES: {draft.versions.join(' · ')}</small><h2>{draft.headline}</h2><label>Legenda</label><p>{draft.caption}</p><label>Direção visual</label><p>{draft.visual}</p><div className="revision"><input value={revision} onChange={e => setRevision(e.target.value)} placeholder="O que deseja alterar?" /><Button onClick={onRevise} secondary>✦ Pedir alteração</Button><Button onClick={onApprove}>✓ Aprovar</Button></div></article>; }
function CreativePanel({ creative, revision, setRevision, onRevise, onApprove }: { creative?: Creative; revision: string; setRevision:(v:string)=>void; onRevise:()=>void; onApprove:()=>void }) { if (!creative) return null; return <aside className="creative-panel"><small>VERSÕES</small><div className="versions">{creative.versions.map(v => <span key={v}>V{v}</span>)}</div><h2>{creative.headline}</h2><p>O renderer preserva headline, CTA, logo e paleta de forma determinística.</p><div className="quick"><button onClick={() => setRevision('Mais clean')}>Mais clean</button><button onClick={() => setRevision('Mais premium')}>Mais premium</button><button onClick={() => setRevision('Outra imagem')}>Outra imagem</button></div><input value={revision} onChange={e => setRevision(e.target.value)} placeholder="O que deseja alterar?" /><Button onClick={onRevise} secondary>✦ Aplicar alteração</Button><Button onClick={onApprove}>✓ Aprovar esta versão</Button></aside>; }
