'use client';

import { useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react';
import { api, ApiError, type ApiBrandProfile, type ApiJob, type ApiStrategy, waitForJob } from '../lib/api';

export type Step = 'home' | 'sources' | 'analyzing' | 'brand' | 'brief' | 'planning' | 'strategy' | 'ideating' | 'ideas' | 'generatingContent' | 'content' | 'production' | 'creatives' | 'result';
export type Idea = { id: string; ordinal: number; title: string; pillar: string; format: string; description: string; promise?: string; targetAudience?: string; creativeAngle?: string; visualDirection?: string; selected: boolean };
export type Draft = { id: string; revisionId: string; headline: string; supportingText?: string; caption: string; cta?: string; visual?: string; approved: boolean; versions: string[] };
export type Creative = { id: string; headline: string; approved: boolean; versions: number[]; activeVersionId?: string; imageUrl?: string; renderedVersions: { id: string; version: number; imageUrl?: string; selected: boolean }[] };
type Project = { id?: string; name: string; campaign: string; step: Step };

const activeProjectStorageKey = 'red-ai-active-project-id';
const loadProjects = (): Project[] => { try { return JSON.parse(localStorage.getItem('red-ai-projects') || '[]') as Project[]; } catch { return []; } };
const projectCard = (project: import('../lib/api').ApiProject): Project => ({ id: project.id, name: project.name, campaign: project.campaign?.name ?? 'Campanha ainda não criada', step: project.currentStep === 'campaign' ? 'brand' : project.currentStep === 'strategy' ? 'strategy' : 'sources' });
const toIdea = (idea: import('../lib/api').ApiIdea): Idea => ({ id: idea.id, ordinal: idea.ordinal, title: idea.title, pillar: idea.pillar, format: idea.contentType, description: idea.description, promise: idea.promise, targetAudience: idea.targetAudience, creativeAngle: idea.creativeAngle, visualDirection: idea.visualDirection, selected: idea.selected });

export function useRedAIWizard() {
  const [step, setStep] = useState<Step>('home');
  const [brand, setBrand] = useState('Cassel Seguros'); const [instagram, setInstagram] = useState('@casselseguros'); const [website, setWebsite] = useState('https://www.casselseguros.com.br'); const [context, setContext] = useState('Corretora de seguros com foco em proteção de famílias e empresas.');
  const [campaign, setCampaign] = useState('Agosto — Proteção e Consórcio'); const [brief, setBrief] = useState('Aproveitar o período de agosto para reforçar a importância do planejamento e da proteção.');
  const [ideas, setIdeas] = useState<Idea[]>([]); const [drafts, setDrafts] = useState<Draft[]>([]); const [creatives, setCreatives] = useState<Creative[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [brandProfile, setBrandProfile] = useState<ApiBrandProfile>(); const [strategy, setStrategy] = useState<ApiStrategy>();
  const [activeDraft, setActiveDraft] = useState(0); const [activeCreative, setActiveCreative] = useState(0); const [revision, setRevision] = useState(''); const [installPrompt, setInstallPrompt] = useState(false); const [aiMode, setAiMode] = useState<string>();
  const [projectId, setProjectId] = useState<string>(); const [campaignId, setCampaignId] = useState<string>(); const [job, setJob] = useState<ApiJob>(); const [error, setError] = useState<string>(); const [retry, setRetry] = useState<(() => void)>(); const [sourceFiles, setSourceFiles] = useState<File[]>([]); const [isRevisingDraft, setIsRevisingDraft] = useState(false); const sourceInputRef = useRef<HTMLInputElement>(null); const restoredContentJobCampaignRef = useRef<string | undefined>(undefined);
  useEffect(() => { setProjects(loadProjects()); void api.projects().then(items => setProjects(items.map(projectCard))).catch(() => undefined); void api.health().then(health => setAiMode(health.aiMode)).catch(() => setAiMode(undefined)); const savedProjectId = localStorage.getItem(activeProjectStorageKey); if (savedProjectId) void Promise.all([api.project(savedProjectId), api.brand(savedProjectId)]).then(async ([project, profile]) => { setProjectId(savedProjectId); setBrandProfile(profile); if (!project.campaign) { setStep('brand'); return; } setCampaignId(project.campaign.id); setCampaign(project.campaign.name); setBrief(project.campaign.context ?? ''); const generatedStrategy = await api.strategy(project.campaign.id); setStrategy(generatedStrategy); const persistedIdeas = await api.ideas(project.campaign.id); setIdeas(persistedIdeas.map(toIdea)); const persistedContent = await api.content(project.campaign.id); if (persistedContent.length) { const loadedDrafts = persistedContent.map(toDraft); setDrafts(loadedDrafts); const creativeVersions = await Promise.all(loadedDrafts.map(draft => api.creatives(draft.id))); if (creativeVersions.some(versions => versions.length)) { setCreatives(loadedDrafts.map((draft, index) => toCreative(draft, creativeVersions[index]))); setStep('creatives'); return; } setStep('content'); return; } setStep(persistedIdeas.length ? 'ideas' : 'strategy'); }).catch(() => localStorage.removeItem(activeProjectStorageKey)); if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined); const handler = (event: Event) => { event.preventDefault(); setInstallPrompt(true); }; window.addEventListener('beforeinstallprompt', handler); return () => window.removeEventListener('beforeinstallprompt', handler); }, []);
  const selected = useMemo(() => ideas.filter(idea => idea.selected), [ideas]); const approvedDrafts = drafts.filter(draft => draft.approved).length;
  const save = (next: Step, id = projectId) => { const entry = { id, name: brand || 'Nova marca', campaign: campaign || 'Campanha sem nome', step: next }; const list = [entry, ...loadProjects().filter(project => project.id ? project.id !== entry.id : project.name !== entry.name)].slice(0, 5); localStorage.setItem('red-ai-projects', JSON.stringify(list)); setProjects(list); };
  const start = () => { localStorage.removeItem(activeProjectStorageKey); setError(undefined); setProjectId(undefined); setCampaignId(undefined); setSourceFiles([]); setIdeas([]); setDrafts([]); setCreatives([]); setBrandProfile(undefined); setStrategy(undefined); setStep('sources'); };
  const nav = (next: Step) => { save(next); setStep(next); };
  const run = (action: () => Promise<void>) => { setError(undefined); setRetry(() => () => { run(action); }); void action().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Ocorreu um erro inesperado.')); };
  const resetDemo = async () => { if (!window.confirm('Limpar todos os projetos e dados da demo? Esta ação não pode ser desfeita.')) return; await api.resetDemo(); localStorage.removeItem('red-ai-projects'); localStorage.removeItem(activeProjectStorageKey); setProjects([]); setProjectId(undefined); setCampaignId(undefined); setBrand(''); setInstagram(''); setWebsite(''); setContext(''); setCampaign(''); setBrief(''); setSourceFiles([]); setIdeas([]); setDrafts([]); setCreatives([]); setBrandProfile(undefined); setStrategy(undefined); setJob(undefined); setError(undefined); setRetry(undefined); setRevision(''); setActiveDraft(0); setActiveCreative(0); setStep('home'); };
  const selectSourceFiles = (event: ChangeEvent<HTMLInputElement>) => { const incoming = Array.from(event.target.files ?? []); setSourceFiles(existing => { const keys = new Set(existing.map(file => `${file.name}:${file.size}:${file.lastModified}`)); return [...existing, ...incoming.filter(file => !keys.has(`${file.name}:${file.size}:${file.lastModified}`))]; }); event.target.value = ''; };
  const removeSourceFile = (index: number) => setSourceFiles(files => files.filter((_, fileIndex) => fileIndex !== index));
  const beginAnalysis = async () => { save('analyzing'); setStep('analyzing'); const project = await api.createProject({ name: brand, instagramHandle: instagram || undefined, websiteUrl: website || undefined, manualContext: context || undefined }); setProjectId(project.id); save('analyzing', project.id); localStorage.setItem(activeProjectStorageKey, project.id); if (sourceFiles.length) await api.uploadSources(project.id, sourceFiles); await waitForJob(await api.analyzeBrand(project.id), setJob); setBrandProfile(await api.brand(project.id)); setStep('brand'); };
  const saveBrandProfile = async (profile: ApiBrandProfile) => { if (!projectId) throw new ApiError('Projeto não encontrado. Reinicie a análise.'); setBrandProfile(await api.saveBrand(projectId, profile)); };
  const approveBrand = async () => { if (!projectId) throw new ApiError('Projeto não encontrado. Reinicie a análise.'); await api.approveBrand(projectId); nav('brief'); };
  const generateStrategy = async () => { if (!projectId) throw new ApiError('Projeto não encontrado. Reinicie a análise.'); setJob(undefined); setStep('planning'); const nextCampaign = campaignId ? { id: campaignId } : await api.createCampaign(projectId, { name: campaign, objective: 'A IA decide a melhor estratégia', targetCount: 5, context: brief }); setCampaignId(nextCampaign.id); await waitForJob(await api.generateStrategy(nextCampaign.id), setJob); setStrategy(await api.strategy(nextCampaign.id)); setStep('strategy'); };
  const generateIdeas = async () => { if (!campaignId) throw new ApiError('Campanha não encontrada.'); setJob(undefined); setStep('ideating'); await api.approveStrategy(campaignId); await waitForJob(await api.generateIdeas(campaignId), setJob); setIdeas((await api.ideas(campaignId)).map(toIdea)); setStep('ideas'); };
  const toggleIdea = async (id: string) => { if (!campaignId) throw new ApiError('Campanha não encontrada.'); const next = ideas.map(idea => ({ ...idea, selected: idea.id === id ? !idea.selected : false })); const saved = await api.selectIdeas(campaignId, next.filter(idea => idea.selected).map(idea => idea.id)); setIdeas(next.map(idea => ({ ...idea, selected: saved.some(item => item.id === idea.id) }))); };
  const toDraft = (item: import('../lib/api').ApiContent): Draft => ({ id: item.contentId, revisionId: item.revisionId, headline: item.headline, supportingText: item.supportingText, caption: item.caption, cta: item.cta, visual: item.visualDirection, approved: item.isApproved, versions: [`V${item.version}`] });
  const finishDraftGeneration = async (contentJob: ApiJob, currentCampaignId: string) => { await waitForJob(contentJob, setJob); setDrafts((await api.content(currentCampaignId)).map(toDraft)); setStep('content'); };
  useEffect(() => { if (!campaignId || restoredContentJobCampaignRef.current === campaignId) return; restoredContentJobCampaignRef.current = campaignId; let cancelled = false; void api.activeContentJob(campaignId).then(async activeJob => { if (!activeJob || cancelled) return; setJob(activeJob); setStep('generatingContent'); await finishDraftGeneration(activeJob, campaignId); }).catch(() => undefined); return () => { cancelled = true; }; }, [campaignId]);
  const generateDrafts = async () => { if (!campaignId) throw new ApiError('Campanha não encontrada.'); setJob(undefined); setStep('generatingContent'); const approved = await api.selectIdeas(campaignId, selected.map(idea => idea.id)); setIdeas(all => all.map(idea => ({ ...idea, selected: approved.some(item => item.id === idea.id) }))); const contentJob = await api.generateContent(campaignId); setRetry(() => () => { run(() => finishDraftGeneration(contentJob, campaignId)); }); await finishDraftGeneration(contentJob, campaignId); };
  const approveAllDrafts = async () => { const approved = await Promise.all(drafts.map(draft => api.approveRevision(draft.id, draft.revisionId))); setDrafts(items => items.map(draft => ({ ...draft, approved: approved.some(revision => revision.id === draft.revisionId && revision.isApproved) }))); };
  const reviseDraft = async () => { if (!revision.trim() || !drafts[activeDraft]) return; setIsRevisingDraft(true); try { const draft = drafts[activeDraft]; const revised = await api.reviseContent(draft.id, revision.trim()); const history = await api.contentItem(draft.id); setDrafts(items => items.map((item, index) => index === activeDraft ? { ...item, revisionId: revised.id, headline: revised.headline, supportingText: revised.supportingText, caption: revised.caption, cta: revised.cta, visual: revised.visualDirection, approved: revised.isApproved, versions: history.revisions.map(entry => `V${entry.version}`) } : item)); setRevision(''); } finally { setIsRevisingDraft(false); } };
  const approveDraft = async () => { const draft = drafts[activeDraft]; if (!draft) return; const approved = await api.approveRevision(draft.id, draft.revisionId); setDrafts(items => items.map((item, index) => index === activeDraft ? { ...item, approved: approved.isApproved } : item)); };
  const toCreative = (draft: Draft, versions: import('../lib/api').ApiCreativeVersion[]): Creative => { const active = versions.find(version => version.isSelected) ?? versions.at(-1); return { id: draft.id, headline: draft.headline, approved: active?.isSelected ?? false, versions: versions.map(version => version.version), activeVersionId: active?.id, imageUrl: active?.imageStorageKey ? api.assetUrl(active.imageStorageKey) : undefined, renderedVersions: versions.map(version => ({ id: version.id, version: version.version, imageUrl: version.imageStorageKey ? api.assetUrl(version.imageStorageKey) : undefined, selected: version.isSelected })) }; };
  const produce = async () => { if (!campaignId) throw new ApiError('Campanha não encontrada.'); setStep('production'); await waitForJob(await api.generateCreatives(campaignId), setJob); setCreatives(await Promise.all(drafts.map(async draft => toCreative(draft, await api.creatives(draft.id))))); setStep('creatives'); };
  const approveCreative = async () => { const creative = creatives[activeCreative]; if (!creative?.activeVersionId) throw new ApiError('Arte não encontrada. Gere as artes novamente.'); const selected = await api.selectCreative(creative.id, creative.activeVersionId); setCreatives(items => items.map((item, index) => index === activeCreative ? { ...item, approved: selected.isSelected, activeVersionId: selected.id } : item)); };
  const selectCreativeVersion = async (versionId: string) => { const creative = creatives[activeCreative]; if (!creative) return; const selected = await api.selectCreative(creative.id, versionId); const versions = await api.creatives(creative.id); setCreatives(items => items.map((item, index) => index === activeCreative ? { ...toCreative({ id: item.id, revisionId: '', headline: item.headline, caption: '', approved: false, versions: [] }, versions), approved: selected.isSelected } : item)); };
  const reviseCreative = async () => { if (!revision.trim() || !creatives[activeCreative]) return; const instruction = revision.trim(); const creative = creatives[activeCreative]; await waitForJob(await api.reviseCreative(creative.id, instruction), setJob); const versions = await api.creatives(creative.id); setCreatives(items => items.map((item, index) => index === activeCreative ? toCreative({ id: item.id, revisionId: '', headline: item.headline, caption: '', approved: false, versions: [] }, versions) : item)); setRevision(''); };
  const exportZip = () => { if (projectId) window.location.assign(api.exportUrl(projectId)); };
  const openProject = async (project: Project) => { const id = project.id ?? localStorage.getItem(activeProjectStorageKey); if (!id) { start(); return; } const [loadedProject, profile] = await Promise.all([api.project(id), api.brand(id)]); setProjectId(id); localStorage.setItem(activeProjectStorageKey, id); setBrand(loadedProject.name); setBrandProfile(profile); if (!loadedProject.campaign) { setStep('brand'); return; } setCampaignId(loadedProject.campaign.id); setCampaign(loadedProject.campaign.name); setBrief(loadedProject.campaign.context ?? ''); const loadedStrategy = await api.strategy(loadedProject.campaign.id); setStrategy(loadedStrategy); const loadedIdeas = await api.ideas(loadedProject.campaign.id); setIdeas(loadedIdeas.map(toIdea)); const activeContentJob = await api.activeContentJob(loadedProject.campaign.id); if (activeContentJob) { setJob(activeContentJob); setStep('generatingContent'); await finishDraftGeneration(activeContentJob, loadedProject.campaign.id); return; } const loadedContent = await api.content(loadedProject.campaign.id); if (!loadedContent.length) { setStep(loadedIdeas.length ? 'ideas' : 'strategy'); return; } const loadedDrafts = loadedContent.map(toDraft); setDrafts(loadedDrafts); const creativeVersions = await Promise.all(loadedDrafts.map(draft => api.creatives(draft.id))); if (creativeVersions.some(versions => versions.length)) { setCreatives(loadedDrafts.map((draft, index) => toCreative(draft, creativeVersions[index]))); setStep('creatives'); return; } setStep('content'); };
  return { step, setStep, brand, setBrand, instagram, setInstagram, website, setWebsite, context, setContext, campaign, setCampaign, brief, setBrief, ideas, drafts, creatives, projects, brandProfile, strategy, activeDraft, setActiveDraft, activeCreative, setActiveCreative, revision, setRevision, installPrompt, aiMode, job, error, setError, retry, sourceFiles, sourceInputRef, isRevisingDraft, selected, approvedDrafts, start, nav, run, resetDemo, selectSourceFiles, removeSourceFile, beginAnalysis, saveBrandProfile, approveBrand, generateStrategy, generateIdeas, toggleIdea, generateDrafts, approveDraft, approveAllDrafts, reviseDraft, produce, approveCreative, selectCreativeVersion, reviseCreative, exportZip, openProject };
}
export type RedAIWizard = ReturnType<typeof useRedAIWizard>;
