'use client';

import { useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react';
import { api, ApiError, type ApiBrandProfile, type ApiJob, type ApiStrategy, waitForJob } from '../lib/api';

export type Step = 'home' | 'sources' | 'analyzing' | 'brand' | 'brief' | 'planning' | 'strategy' | 'ideating' | 'ideas' | 'content' | 'production' | 'creatives' | 'result';
export type Idea = { id: string; ordinal: number; title: string; pillar: string; format: string; description: string; selected: boolean };
export type Draft = { id: string; revisionId: string; headline: string; supportingText?: string; caption: string; cta?: string; visual?: string; approved: boolean; versions: string[] };
export type Creative = { id: string; headline: string; approved: boolean; versions: number[]; color: string };
type Project = { name: string; campaign: string; step: Step };

const colors = ['#082b55', '#123f74', '#f25b35', '#12304b', '#1d5ca0', '#eb6a36', '#1b4369', '#082039', '#d95032', '#386798', '#0c315b', '#ef5e33'];
const activeProjectStorageKey = 'red-ai-active-project-id';
const loadProjects = (): Project[] => { try { return JSON.parse(localStorage.getItem('red-ai-projects') || '[]') as Project[]; } catch { return []; } };

export function useRedAIWizard() {
  const [step, setStep] = useState<Step>('home');
  const [brand, setBrand] = useState('Cassel Seguros'); const [instagram, setInstagram] = useState('@casselseguros'); const [website, setWebsite] = useState('https://www.casselseguros.com.br'); const [context, setContext] = useState('Corretora de seguros com foco em proteção de famílias e empresas.');
  const [campaign, setCampaign] = useState('Agosto — Proteção e Consórcio'); const [brief, setBrief] = useState('Aproveitar o período de agosto para reforçar a importância do planejamento e da proteção.');
  const [ideas, setIdeas] = useState<Idea[]>([]); const [drafts, setDrafts] = useState<Draft[]>([]); const [creatives, setCreatives] = useState<Creative[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [brandProfile, setBrandProfile] = useState<ApiBrandProfile>(); const [strategy, setStrategy] = useState<ApiStrategy>();
  const [activeDraft, setActiveDraft] = useState(0); const [activeCreative, setActiveCreative] = useState(0); const [revision, setRevision] = useState(''); const [installPrompt, setInstallPrompt] = useState(false); const [aiMode, setAiMode] = useState<string>();
  const [projectId, setProjectId] = useState<string>(); const [campaignId, setCampaignId] = useState<string>(); const [job, setJob] = useState<ApiJob>(); const [error, setError] = useState<string>(); const [retry, setRetry] = useState<(() => void)>(); const [sourceFiles, setSourceFiles] = useState<File[]>([]); const sourceInputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { setProjects(loadProjects()); void api.health().then(health => setAiMode(health.aiMode)).catch(() => setAiMode(undefined)); const savedProjectId = localStorage.getItem(activeProjectStorageKey); if (savedProjectId) void Promise.all([api.project(savedProjectId), api.brand(savedProjectId)]).then(async ([project, profile]) => { setProjectId(savedProjectId); setBrandProfile(profile); if (!project.campaign) { setStep('brand'); return; } setCampaignId(project.campaign.id); setCampaign(project.campaign.name); setBrief(project.campaign.context ?? ''); const generatedStrategy = await api.strategy(project.campaign.id); setStrategy(generatedStrategy); const persistedIdeas = await api.ideas(project.campaign.id); setIdeas(persistedIdeas.map(idea => ({ id: idea.id, ordinal: idea.ordinal, title: idea.title, pillar: idea.pillar, format: idea.contentType, description: idea.description, selected: idea.selected }))); const persistedContent = await api.content(project.campaign.id); if (persistedContent.length) { setDrafts(persistedContent.map(toDraft)); setStep('content'); return; } setStep(persistedIdeas.length ? 'ideas' : 'strategy'); }).catch(() => localStorage.removeItem(activeProjectStorageKey)); if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined); const handler = (event: Event) => { event.preventDefault(); setInstallPrompt(true); }; window.addEventListener('beforeinstallprompt', handler); return () => window.removeEventListener('beforeinstallprompt', handler); }, []);
  const selected = useMemo(() => ideas.filter(idea => idea.selected), [ideas]); const approvedDrafts = drafts.filter(draft => draft.approved).length;
  const save = (next: Step) => { const entry = { name: brand || 'Nova marca', campaign: campaign || 'Campanha sem nome', step: next }; const list = [entry, ...loadProjects().filter(project => project.name !== entry.name)].slice(0, 5); localStorage.setItem('red-ai-projects', JSON.stringify(list)); setProjects(list); };
  const start = () => { localStorage.removeItem(activeProjectStorageKey); setError(undefined); setProjectId(undefined); setCampaignId(undefined); setSourceFiles([]); setIdeas([]); setDrafts([]); setCreatives([]); setBrandProfile(undefined); setStrategy(undefined); setStep('sources'); };
  const nav = (next: Step) => { save(next); setStep(next); };
  const run = (action: () => Promise<void>) => { setError(undefined); setRetry(() => () => { run(action); }); void action().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Ocorreu um erro inesperado.')); };
  const resetDemo = async () => { if (!window.confirm('Limpar todos os projetos e dados da demo? Esta ação não pode ser desfeita.')) return; await api.resetDemo(); localStorage.removeItem('red-ai-projects'); setProjects([]); start(); };
  const selectSourceFiles = (event: ChangeEvent<HTMLInputElement>) => { const incoming = Array.from(event.target.files ?? []); setSourceFiles(existing => { const keys = new Set(existing.map(file => `${file.name}:${file.size}:${file.lastModified}`)); return [...existing, ...incoming.filter(file => !keys.has(`${file.name}:${file.size}:${file.lastModified}`))]; }); event.target.value = ''; };
  const removeSourceFile = (index: number) => setSourceFiles(files => files.filter((_, fileIndex) => fileIndex !== index));
  const beginAnalysis = async () => { save('analyzing'); setStep('analyzing'); const project = await api.createProject({ name: brand, instagramHandle: instagram || undefined, websiteUrl: website || undefined, manualContext: context || undefined }); setProjectId(project.id); localStorage.setItem(activeProjectStorageKey, project.id); if (sourceFiles.length) await api.uploadSources(project.id, sourceFiles); await waitForJob(await api.analyzeBrand(project.id), setJob); setBrandProfile(await api.brand(project.id)); setStep('brand'); };
  const saveBrandProfile = async (profile: ApiBrandProfile) => { if (!projectId) throw new ApiError('Projeto não encontrado. Reinicie a análise.'); setBrandProfile(await api.saveBrand(projectId, profile)); };
  const approveBrand = async () => { if (!projectId) throw new ApiError('Projeto não encontrado. Reinicie a análise.'); await api.approveBrand(projectId); nav('brief'); };
  const generateStrategy = async () => { if (!projectId) throw new ApiError('Projeto não encontrado. Reinicie a análise.'); setJob(undefined); setStep('planning'); const nextCampaign = campaignId ? { id: campaignId } : await api.createCampaign(projectId, { name: campaign, objective: 'A IA decide a melhor estratégia', targetCount: 12, context: brief }); setCampaignId(nextCampaign.id); await waitForJob(await api.generateStrategy(nextCampaign.id), setJob); setStrategy(await api.strategy(nextCampaign.id)); setStep('strategy'); };
  const generateIdeas = async () => { if (!campaignId) throw new ApiError('Campanha não encontrada.'); setJob(undefined); setStep('ideating'); await api.approveStrategy(campaignId); await waitForJob(await api.generateIdeas(campaignId), setJob); setIdeas((await api.ideas(campaignId)).map(idea => ({ id: idea.id, ordinal: idea.ordinal, title: idea.title, pillar: idea.pillar, format: idea.contentType, description: idea.description, selected: idea.selected }))); setStep('ideas'); };
  const toggleIdea = async (id: string) => { if (!campaignId) throw new ApiError('Campanha não encontrada.'); const next = ideas.map(idea => idea.id === id ? { ...idea, selected: idea.selected ? false : ideas.filter(item => item.selected).length < 12 } : idea); const saved = await api.selectIdeas(campaignId, next.filter(idea => idea.selected).map(idea => idea.id)); setIdeas(next.map(idea => ({ ...idea, selected: saved.some(item => item.id === idea.id) }))); };
  const toDraft = (item: import('../lib/api').ApiContent): Draft => ({ id: item.contentId, revisionId: item.revisionId, headline: item.headline, supportingText: item.supportingText, caption: item.caption, cta: item.cta, visual: item.visualDirection, approved: item.isApproved, versions: [`V${item.version}`] });
  const generateDrafts = async () => { if (!campaignId) throw new ApiError('Campanha não encontrada.'); const approved = await api.selectIdeas(campaignId, selected.map(idea => idea.id)); setIdeas(all => all.map(idea => ({ ...idea, selected: approved.some(item => item.id === idea.id) }))); await waitForJob(await api.generateContent(campaignId), setJob); setDrafts((await api.content(campaignId)).map(toDraft)); setStep('content'); };
  const approveAllDrafts = async () => { const approved = await Promise.all(drafts.map(draft => api.approveRevision(draft.id, draft.revisionId))); setDrafts(items => items.map(draft => ({ ...draft, approved: approved.some(revision => revision.id === draft.revisionId && revision.isApproved) }))); };
  const reviseDraft = async () => { if (!revision.trim() || !drafts[activeDraft]) return; const draft = drafts[activeDraft]; const revised = await api.reviseContent(draft.id, revision.trim()); const history = await api.contentItem(draft.id); setDrafts(items => items.map((item, index) => index === activeDraft ? { ...item, revisionId: revised.id, headline: revised.headline, supportingText: revised.supportingText, caption: revised.caption, cta: revised.cta, visual: revised.visualDirection, approved: revised.isApproved, versions: history.revisions.map(entry => `V${entry.version}`) } : item)); setRevision(''); };
  const approveDraft = async () => { const draft = drafts[activeDraft]; if (!draft) return; const approved = await api.approveRevision(draft.id, draft.revisionId); setDrafts(items => items.map((item, index) => index === activeDraft ? { ...item, approved: approved.isApproved } : item)); };
  const produce = async () => { if (!campaignId) throw new ApiError('Campanha não encontrada.'); setStep('production'); await waitForJob(await api.generateCreatives(campaignId), setJob); setCreatives(drafts.map((draft, index) => ({ id: draft.id, headline: draft.headline, approved: false, versions: [1], color: colors[index % colors.length] }))); setStep('creatives'); };
  const approveCreative = () => setCreatives(items => items.map((creative, index) => index === activeCreative ? { ...creative, approved: true } : creative));
  const reviseCreative = async () => { if (!revision.trim() || !creatives[activeCreative]) return; const instruction = revision.trim(); await waitForJob(await api.reviseCreative(creatives[activeCreative].id, instruction), setJob); setCreatives(items => items.map((creative, index) => index === activeCreative ? { ...creative, versions: [...creative.versions, creative.versions.length + 1] } : creative)); setRevision(''); };
  const exportZip = () => { if (projectId) window.location.assign(api.exportUrl(projectId)); };
  const openProject = (project: Project) => { setBrand(project.name); setCampaign(project.campaign); project.step === 'result' ? setStep('result') : start(); };
  return { step, setStep, brand, setBrand, instagram, setInstagram, website, setWebsite, context, setContext, campaign, setCampaign, brief, setBrief, ideas, drafts, creatives, projects, brandProfile, strategy, activeDraft, setActiveDraft, activeCreative, setActiveCreative, revision, setRevision, installPrompt, aiMode, job, error, setError, retry, sourceFiles, sourceInputRef, selected, approvedDrafts, start, nav, run, resetDemo, selectSourceFiles, removeSourceFile, beginAnalysis, saveBrandProfile, approveBrand, generateStrategy, generateIdeas, toggleIdea, generateDrafts, approveDraft, approveAllDrafts, reviseDraft, produce, approveCreative, reviseCreative, exportZip, openProject };
}
export type RedAIWizard = ReturnType<typeof useRedAIWizard>;
