'use client';

import type { ReactNode } from 'react';
import type { RedAIWizard, Step, Draft, Creative } from './useRedAIWizard';

type Props = { wizard: RedAIWizard };
function Button({ children, onClick, disabled, secondary = false }: { children: ReactNode; onClick: () => void; disabled?: boolean; secondary?: boolean }) { return <button className={secondary ? 'button secondary' : 'button'} disabled={disabled} onClick={onClick}>{children}</button>; }
function Field({ label, value, onChange, optional, area = false }: { label: string; value: string; onChange: (value: string) => void; optional?: boolean; area?: boolean }) { const props = { value, onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => onChange(event.target.value), placeholder: label }; return <label className="field"><span>{label}{optional && <i> opcional</i>}</span>{area ? <textarea {...props} rows={4} /> : <input {...props} />}</label>; }
function StepTitle({ n, title, text }: { n: string; title: string; text: string }) { return <div className="step-title"><span>{n}</span><div><h1>{title}</h1><p>{text}</p></div></div>; }
function Trait({ title, items, onRemove }: { title: string; items: string[]; onRemove?: (item: string) => void }) { return <div className="trait"><label>{title}</label><div>{items.map(item => <button key={item} onClick={() => onRemove?.(item)}>{item}</button>)}</div></div>; }
function Footer({ back, next, onNext, disabled }: { back?: () => void; next: string; onNext: () => void; disabled?: boolean }) { return <footer>{back ? <Button secondary onClick={back}>← Voltar</Button> : <span />}<Button onClick={onNext} disabled={disabled}>{next}</Button></footer>; }

export function WizardShell({ wizard }: Props) { return <main><Header onProjects={() => wizard.setStep('home')} install={wizard.installPrompt} aiMode={wizard.aiMode} /><WizardProgress step={wizard.step} />{wizard.error && <div className="api-error" role="alert"><span>{wizard.error}</span><Button secondary onClick={() => wizard.retry?.()}>Tentar novamente</Button><button aria-label="Fechar erro" onClick={() => wizard.setError(undefined)}>×</button></div>}<section className="wizard"><WizardStep wizard={wizard} /></section></main>; }
function WizardStep({ wizard }: Props) { switch (wizard.step) { case 'sources': return <SourcesStep wizard={wizard} />; case 'analyzing': return <AnalysisStep wizard={wizard} />; case 'brand': return <BrandStep wizard={wizard} />; case 'brief': return <CampaignBriefStep wizard={wizard} />; case 'planning': return <PlanningStep wizard={wizard} />; case 'strategy': return <StrategyStep wizard={wizard} />; case 'ideating': return <IdeasGenerationStep wizard={wizard} />; case 'ideas': return <IdeasStep wizard={wizard} />; case 'generatingContent': return <ContentGenerationStep wizard={wizard} />; case 'content': return <ContentReviewStep wizard={wizard} />; case 'production': return <ProductionStep wizard={wizard} />; case 'creatives': return <CreativeReviewStep wizard={wizard} />; case 'result': return <ResultStep wizard={wizard} />; default: return null; } }
export function HomeStep({ wizard }: Props) { return <main className="home"><Header onProjects={() => undefined} install={wizard.installPrompt} aiMode={wizard.aiMode} /><section className="hero"><p className="eyebrow">CAMPANHAS QUE COMEÇAM COM CONTEXTO</p><h1>Transforme qualquer marca em uma campanha com IA.</h1><p>Da identidade ao resultado final. Com direção humana em cada escolha que importa.</p><Button onClick={wizard.start}>+ Nova análise</Button></section><section className="recent"><div className="section-title"><div className="section-heading"><h2>Projetos recentes</h2><span>{wizard.aiMode ? `Modo ${wizard.aiMode} ativo` : 'Conectando à IA…'}</span></div><div className="section-actions"><button className="reset-demo" onClick={() => wizard.run(wizard.resetDemo)}>Limpar demo</button></div></div><div className="project-grid">{wizard.projects.slice(0, 4).map((project, index) => <article className="project-card" key={project.id ?? `${project.name}-${index}`}><div className="project-mark">{project.name.slice(0, 2).toUpperCase()}</div><small>{project.step === 'result' ? 'CONCLUÍDO' : 'EM ANDAMENTO'}</small><h3 title={project.name}>{project.name}</h3><p title={project.campaign}>{project.campaign}</p><button onClick={() => wizard.run(() => wizard.openProject(project))}>Continuar <b>→</b></button></article>)}</div></section></main>; }
export function SourcesStep({ wizard }: Props) { return <><StepTitle n="01" title="Fontes da Marca" text="Envie o contexto que ajuda a IA a entender sua marca." /><div className="form-grid"><Field label="Nome da marca" value={wizard.brand} onChange={wizard.setBrand} /><Field label="Instagram (@)" value={wizard.instagram} onChange={wizard.setInstagram} optional /><Field label="Site" value={wizard.website} onChange={wizard.setWebsite} optional /><Field label="Sobre a marca" value={wizard.context} onChange={wizard.setContext} optional area /></div><input ref={wizard.sourceInputRef} id="brand-sources" className="file-input" type="file" multiple accept="image/png,image/jpeg,image/webp,application/pdf,image/svg+xml" onChange={wizard.selectSourceFiles} /><button type="button" className="uploader" onClick={() => wizard.sourceInputRef.current?.click()} aria-describedby="brand-sources-help"><span className="upload-icon" aria-hidden="true">⇧</span><strong>Clique para enviar materiais da marca</strong><span id="brand-sources-help">PNG, JPG, WEBP, PDF ou SVG. Você pode selecionar mais de uma vez.</span></button>{wizard.sourceFiles.length > 0 && <ul className="source-files" aria-label="Arquivos selecionados">{wizard.sourceFiles.map((file, index) => <li key={`${file.name}-${file.size}-${file.lastModified}`}><span>{file.name}</span><small>{Math.ceil(file.size / 1024)} KB</small><button type="button" onClick={() => wizard.removeSourceFile(index)} aria-label={`Remover ${file.name}`}>×</button></li>)}</ul>}<Footer next="✦ Mapear identidade" onNext={() => wizard.run(wizard.beginAnalysis)} /></>; }
export function AnalysisStep({ wizard }: Props) { const job = wizard.job; const failed = wizard.error || job?.error; return <><StepTitle n="02" title="Analisando a Marca" text="Acompanhe o status real do processamento." /><div className="analysis" role="status" aria-live="polite"><div className={`ring${failed ? '' : ' active'}`}><strong>{failed ? '×' : job ? `${job.progress}%` : '…'}</strong><span>{failed ? 'Análise não concluída' : job?.message ?? 'Aguardando a resposta da análise'}</span></div><div className="checks">{failed ? <p className="error">Erro retornado pela API: {failed}</p> : job ? <><p>{job.status === 'completed' ? '✓' : job.status === 'failed' ? '×' : '○'} Status: {job.status}</p><p>Etapas concluídas: {job.completedSteps} de {job.totalSteps}</p></> : <p>Os materiais estão sendo enviados e analisados. Esta tela só avança quando a API concluir; qualquer falha será exibida aqui.</p>}</div></div></>; }
export function PlanningStep({ wizard }: Props) { const job = wizard.job; const failed = wizard.error || job?.error; return <><StepTitle n="04" title="Planejando a Campanha" text="Estamos criando a estratégia a partir do Brand DNA aprovado e do briefing." /><div className="analysis" role="status" aria-live="polite"><div className={`ring${failed ? '' : ' active'}`}><strong>{failed ? '×' : job ? `${job.progress}%` : '…'}</strong><span>{failed ? 'Planejamento não concluído' : job?.message ?? 'Criando estratégia com IA'}</span></div><div className="checks">{failed ? <p className="error">Erro retornado pela API: {failed}</p> : job ? <><p>{job.status === 'completed' ? '✓' : job.status === 'failed' ? '×' : '○'} Status: {job.status}</p><p>Etapas concluídas: {job.completedSteps} de {job.totalSteps}</p></> : <p>O briefing foi enviado. A IA está combinando objetivo, contexto e Brand DNA; a estratégia aparecerá assim que a API concluir.</p>}</div></div></>; }
export function IdeasGenerationStep({ wizard }: Props) { const job = wizard.job; const failed = wizard.error || job?.error; const statusText = job?.status === 'queued' ? 'Na fila de processamento' : job?.status === 'running' ? 'Gerando 15 ideias em uma chamada à IA' : job?.message ?? 'Criando ideias com IA'; return <><StepTitle n="06" title="Gerando Ideias" text="A estratégia aprovada está sendo transformada em 15 ideias de conteúdo." /><div className="analysis" role="status" aria-live="polite"><div className={`ring${failed ? '' : ' active'}`}><strong>{failed ? '×' : job?.status === 'completed' ? '✓' : '…'}</strong><span>{failed ? 'Geração não concluída' : statusText}</span></div><div className="checks">{failed ? <p className="error">Erro retornado pela API: {failed}</p> : job ? <p>{job.status === 'completed' ? '✓' : job.status === 'failed' ? '×' : '○'} {statusText}</p> : <p>A estratégia foi aprovada. A API está gerando e validando as 15 ideias antes de mostrar a seleção.</p>}</div></div></>; }
export function ContentGenerationStep({ wizard }: Props) {
  const job = wizard.job;
  const failed = wizard.error || job?.error;
  const completed = job?.completedSteps ?? 0;
  const total = job?.totalSteps || 5;
  const statusText = job?.status === 'queued'
    ? 'Na fila de processamento'
    : job?.status === 'running'
      ? job.message || `Gerando conteúdo ${completed} de ${total}`
      : job?.message ?? 'Preparando conteúdo para revisão';

  return <><StepTitle n="07" title="Gerando Conteúdos" text="Cada ideia selecionada receberá uma primeira versão de copy para revisão." /><div className="analysis" role="status" aria-live="polite"><div className={`ring${failed ? '' : ' active'}`}><strong>{failed ? '×' : job?.status === 'completed' ? '✓' : `${completed}/${total}`}</strong><span>{failed ? 'Geração não concluída' : statusText}</span></div><div className="checks">{failed ? <p className="error">Erro retornado pela API: {failed}</p> : job ? <p>{job.status === 'completed' ? '✓' : '○'} {statusText}</p> : <p>As 5 ideias selecionadas foram enviadas. A tela de revisão abrirá quando a API persistir todas as versões V1.</p>}</div></div></>;
}
export function BrandStep({ wizard }: Props) { const profile = wizard.brandProfile; const removeTrait = (trait: string) => { if (!profile) return; wizard.run(() => wizard.saveBrandProfile({ ...profile, voice: { ...profile.voice, traits: profile.voice.traits?.filter(item => item !== trait) } })); }; return <><StepTitle n="03" title="Brand DNA" text={`É assim que entendemos a ${wizard.brand}. Ajuste o que for necessário.`} /><div className="two-col"><div className="panel"><label>Paleta de cores</label><div className="palette">{profile?.visualIdentity.colors?.map(color => <i key={color.hex} style={{ background: color.hex }} />)}</div><Trait title="Personalidade" items={profile?.voice.traits ?? []} onRemove={removeTrait} /><Trait title="Tom de voz" items={profile?.voice.traits ?? []} onRemove={removeTrait} /><Trait title="Público provável" items={profile?.audiences?.map(audience => audience.name) ?? []} /></div><div className="panel"><label>Produtos e oportunidades</label><Trait title="Principais produtos" items={profile?.products?.map(product => product.name) ?? []} /><p className="detail">{profile?.contentAnalysis?.recommendations?.join(' · ')}</p><Trait title="Evitar" items={[...(profile?.voice.avoid ?? []), ...(profile?.restrictions ?? [])]} /></div></div><Footer back={() => wizard.nav('sources')} next="Usar este Brand DNA →" onNext={() => wizard.run(wizard.approveBrand)} /></>; }
export function CampaignBriefStep({ wizard }: Props) { return <><StepTitle n="04" title="Planejando a Campanha" text="Vamos definir os objetivos e o contexto." /><div className="form-grid"><Field label="Nome da campanha" value={wizard.campaign} onChange={wizard.setCampaign} /><Field label="Objetivo" value="A IA decide a melhor estratégia" onChange={() => undefined} /><Field label="Quantidade final" value="5 conteúdos" onChange={() => undefined} /><Field label="Período" value="Agosto 2026" onChange={() => undefined} /><Field label="Contexto adicional" value={wizard.brief} onChange={wizard.setBrief} optional area /></div><Footer back={() => wizard.nav('brand')} next="✦ Planejar campanha" onNext={() => wizard.run(wizard.generateStrategy)} /></>; }
export function StrategyStep({ wizard }: Props) { const strategy = wizard.strategy; return <><StepTitle n="05" title="Estratégia Proposta" text="Nossa estratégia para atingir o objetivo." /><div className="strategy"><div className="panel"><small>OBJETIVO DA CAMPANHA</small><h2>{strategy?.strategicObjective}</h2><p>{strategy?.rationale}</p></div><div className="panel"><small>MIX DE CONTEÚDO</small>{strategy?.contentMix.map(item => <div className="mix" key={item.pillar}><span>{item.pillar}</span><b>{item.percentage}%</b><i style={{ width: `${item.percentage}%` }} /></div>)}</div></div><Trait title="Pilares de conteúdo" items={strategy?.pillars.map(pillar => pillar.name) ?? []} /><Footer back={() => wizard.nav('brief')} next="Aprovar estratégia →" onNext={() => wizard.run(wizard.generateIdeas)} /></>; }
export function IdeasStep({ wizard }: Props) { return <><StepTitle n="06" title="15 Ideias de Conteúdo" text="Selecione as 5 melhores ideias para a campanha." /><div className="selection"><b>Selecionadas: <em>{wizard.selected.length} / 5</em></b><span>{wizard.selected.length === 5 ? 'Seleção completa' : 'Escolha exatamente 5'}</span></div><div className="filters"><button>Todos</button><button>Educação</button><button>Autoridade</button><button>Conversão</button></div><div className="idea-list">{wizard.ideas.map(idea => <article className={`idea ${idea.selected ? 'selected' : ''}`} key={idea.id} onClick={() => wizard.run(() => wizard.toggleIdea(idea.id))}><span>{String(idea.ordinal).padStart(2, '0')}</span><div><h3>{idea.title}</h3><p>{idea.description}</p><small>{idea.pillar} · {idea.format}</small></div><b>{idea.selected ? '✓' : '○'}</b></article>)}</div><Footer back={() => wizard.nav('strategy')} next="Continuar com 5 →" disabled={wizard.selected.length !== 5} onNext={() => wizard.run(wizard.generateDrafts)} /></>; }
export function ContentReviewStep({ wizard }: Props) { return <><StepTitle n="07" title="Conteúdo Proposto" text="Revise os textos antes de gerar as artes." /><div className="content-layout"><aside>{wizard.drafts.map((draft, index) => <button className={index === wizard.activeDraft ? 'active' : ''} key={draft.id} onClick={() => wizard.setActiveDraft(index)}><b>{String(index + 1).padStart(2, '0')}</b>{draft.headline}<span>{draft.approved ? '✓' : '○'}</span></button>)}</aside><DraftPanel draft={wizard.drafts[wizard.activeDraft]} wizard={wizard} /></div><div className="approval"><span>{wizard.approvedDrafts}/5 aprovados</span><Button onClick={() => wizard.run(wizard.approveAllDrafts)} secondary>Aprovar todos</Button></div><Footer back={() => wizard.nav('ideas')} next="✦ Gerar artes" disabled={wizard.approvedDrafts !== 5} onNext={() => wizard.run(wizard.produce)} /></>; }
function DraftPanel({ draft, wizard }: { draft?: Draft; wizard: RedAIWizard }) { if (!draft) return null; return <article className="draft-panel"><small>VERSÕES: {draft.versions.join(' · ')}</small><h2>{draft.headline}</h2>{draft.supportingText && <><label>Texto de apoio</label><p>{draft.supportingText}</p></>}<label>Legenda</label><p>{draft.caption}</p>{draft.cta && <><label>CTA</label><p>{draft.cta}</p></>}{draft.visual && <><label>Direção visual</label><p>{draft.visual}</p></>}<div className="revision"><input value={wizard.revision} onChange={event => wizard.setRevision(event.target.value)} placeholder="O que deseja alterar?" disabled={wizard.isRevisingDraft} /><Button onClick={() => wizard.run(wizard.reviseDraft)} secondary disabled={wizard.isRevisingDraft}>{wizard.isRevisingDraft ? 'Revisando com IA…' : '✦ Pedir alteração'}</Button><Button onClick={() => wizard.run(wizard.approveDraft)} disabled={wizard.isRevisingDraft}>✓ Aprovar</Button></div>{wizard.isRevisingDraft && <p className="revision-status" role="status">A IA está criando uma nova versão. A V1 permanecerá preservada.</p>}</article>; }
export function ProductionStep({ wizard }: Props) { const job = wizard.job; const completed = job?.completedSteps ?? 0; const total = job?.totalSteps || 5; return <><StepTitle n="08" title="Produzindo as Artes" text="As artes são renderizadas e persistidas individualmente." /><div className="production" role="status" aria-live="polite"><div className={`ring${job?.status === 'failed' ? '' : ' active'}`}><strong>{job?.status === 'failed' ? '×' : job?.status === 'completed' ? '✓' : `${completed}/${total}`}</strong><span>{job?.status === 'failed' ? 'Produção não concluída' : job?.message ?? 'Na fila de processamento'}</span></div><p>{job?.status === 'failed' ? job.error ?? 'A API não concluiu a produção.' : `Artes concluídas: ${completed} de ${total}`}</p></div></>; }
export function CreativeReviewStep({ wizard }: Props) { return <><StepTitle n="09" title="Revisão das Artes" text="Confira as artes renderizadas antes de concluir a campanha." /><div className="creative-layout"><div className="creative-grid">{wizard.creatives.map((creative, index) => <button className={`creative-card ${index === wizard.activeCreative ? 'active' : ''}`} key={creative.id} onClick={() => wizard.setActiveCreative(index)}><strong>{creative.headline}</strong><span className="creative-preview" style={creative.imageUrl ? { backgroundImage: `url(${creative.imageUrl})` } : undefined}><small>{String(index + 1).padStart(2, '0')}</small><i>{creative.approved ? '● Aprovado' : '○ Em revisão'}</i></span></button>)}</div><CreativePanel creative={wizard.creatives[wizard.activeCreative]} wizard={wizard} /></div><Footer back={() => wizard.nav('content')} next="Ver resultado final →" disabled={wizard.creatives.some(creative => !creative.approved)} onNext={() => wizard.nav('result')} /></>; }
function CreativePanel({ creative, wizard }: { creative?: Creative; wizard: RedAIWizard }) { if (!creative) return null; return <aside className="creative-panel"><small>VERSÕES RENDERIZADAS</small><div className="versions">{creative.renderedVersions.map(version => <button className={version.id === creative.activeVersionId ? 'active' : ''} key={version.id} onClick={() => wizard.run(() => wizard.selectCreativeVersion(version.id))}>V{version.version}</button>)}</div><h2>{creative.headline}</h2><p>{creative.imageUrl ? 'A arte exibida foi carregada do arquivo PNG persistido.' : 'A versão renderizada ainda não está disponível.'}</p><div className="quick"><button onClick={() => wizard.setRevision('Deixe o fundo mais claro e o título menor.')}>Mais espaço</button><button onClick={() => wizard.setRevision('Troque a foto por uma família.')}>Trocar foto</button></div><input value={wizard.revision} onChange={event => wizard.setRevision(event.target.value)} placeholder="O que deseja alterar visualmente?" /><Button onClick={() => wizard.run(wizard.reviseCreative)} secondary disabled={!wizard.revision.trim()}>✦ Criar nova versão</Button><Button onClick={() => wizard.run(wizard.approveCreative)} disabled={!creative.activeVersionId || creative.approved}>✓ {creative.approved ? 'Versão aprovada' : 'Aprovar esta versão'}</Button></aside>; }
export function ResultStep({ wizard }: Props) { return <><div className="result-head"><p className="eyebrow">CAMPANHA FINALIZADA</p><h1>Campanha pronta.</h1><p>{wizard.creatives.length} conteúdos com estratégia, copy e direção criativa alinhadas.</p><Button onClick={wizard.exportZip}>↓ Baixar campanha .ZIP</Button></div><div className="result-grid">{wizard.creatives.map((creative, index) => <article className="creative-card result-card" key={creative.id}><strong>{creative.headline}</strong><span className="creative-preview" style={creative.imageUrl ? { backgroundImage: `url(${creative.imageUrl})` } : undefined}><small>{String(index + 1).padStart(2, '0')}</small><i>● Aprovado</i></span></article>)}</div><Footer back={() => wizard.nav('creatives')} next="Nova análise →" onNext={wizard.start} /></>; }
function Header({ onProjects, install, aiMode }: { onProjects: () => void; install: boolean; aiMode?: string }) { return <header><button className="logo" onClick={onProjects}>RED <b>AI</b></button><nav><span>AI_MODE: <b>{aiMode?.toUpperCase() ?? '…'}</b></span>{install && <span className="install">Instalável</span>}<button onClick={onProjects}>Projetos</button></nav></header>; }
export function WizardProgress({ step }: { step: Step }) { const steps: [string, Step[]][] = [['01 Marca', ['sources', 'analyzing', 'brand']], ['02 Estratégia', ['brief', 'planning', 'strategy']], ['03 Ideias', ['ideating', 'ideas']], ['04 Conteúdo', ['generatingContent', 'content']], ['05 Artes', ['production', 'creatives']], ['06 Resultado', ['result']]]; return <div className="progress">{steps.map(([name, mapped], index) => <span className={mapped.includes(step) ? 'now' : steps.slice(0, index).some(([, values]) => values.includes(step)) ? 'past' : ''} key={name}>{name}</span>)}</div>; }
