namespace RedAI.Domain;

public sealed class Project { public Guid Id { get; init; } = Guid.NewGuid(); public required string Name { get; set; } public string? InstagramHandle { get; set; } public string? WebsiteUrl { get; set; } public string? ManualContext { get; set; } public string CurrentStep { get; set; } = "sources"; public string Status { get; set; } = "active"; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; public Campaign? Campaign { get; set; } }
public sealed class Campaign { public Guid Id { get; init; } = Guid.NewGuid(); public required Guid ProjectId { get; init; } public required string Name { get; set; } public string Objective { get; set; } = "AI decide"; public int TargetCount { get; set; } = 12; public string? Context { get; set; } public bool StrategyApproved { get; set; } public List<ContentIdea> Ideas { get; } = []; }
public sealed class ContentIdea { public Guid Id { get; init; } = Guid.NewGuid(); public Guid CampaignId { get; init; } public int Ordinal { get; init; } public required string Title { get; init; } public required string Pillar { get; init; } public required string ContentType { get; init; } public required string Description { get; init; } public bool Selected { get; set; } }
public sealed class Job { public Guid Id { get; init; } = Guid.NewGuid(); public required string Type { get; init; } public required string EntityType { get; init; } public Guid EntityId { get; init; } public string Status { get; set; } = "queued"; public int Progress { get; set; } public int CompletedSteps { get; set; } public int TotalSteps { get; init; } = 1; public string? Message { get; set; } public string? Error { get; set; } public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow; public DateTimeOffset? CompletedAt { get; set; } }
public sealed class AIRun { public Guid Id { get; init; } = Guid.NewGuid(); public required string Operation { get; init; } public required string EntityType { get; init; } public Guid EntityId { get; init; } public required string Model { get; init; } public required string InputJson { get; init; } public string? OutputJson { get; set; } public string Status { get; set; } = "running"; public string? Error { get; set; } public DateTimeOffset StartedAt { get; init; } = DateTimeOffset.UtcNow; public DateTimeOffset? CompletedAt { get; set; } }
public sealed class BrandSource { public Guid Id { get; init; } = Guid.NewGuid(); public Guid ProjectId { get; init; } public string Type { get; set; } = "manual"; public string? OriginalFilename { get; set; } public string? StorageKey { get; set; } public string? MimeType { get; set; } public string? ExtractedText { get; set; } public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow; }
public sealed class BrandProfile { public Guid Id { get; init; } = Guid.NewGuid(); public Guid ProjectId { get; init; } public required string ProfileJson { get; set; } public decimal Confidence { get; set; } public string Status { get; set; } = "generated"; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class CampaignStrategy { public Guid Id { get; init; } = Guid.NewGuid(); public Guid CampaignId { get; init; } public required string StrategyJson { get; set; } public string Status { get; set; } = "generated"; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ContentItem { public Guid Id { get; init; } = Guid.NewGuid(); public Guid CampaignId { get; init; } public Guid SourceIdeaId { get; init; } public int Sequence { get; init; } public string Status { get; set; } = "generated"; public Guid? ApprovedRevisionId { get; set; } }
public sealed class ContentRevision { public Guid Id { get; init; } = Guid.NewGuid(); public Guid ContentItemId { get; init; } public int Version { get; init; } public required string Headline { get; set; } public required string Caption { get; set; } public string? SupportingText { get; set; } public string? Cta { get; set; } public string HashtagsJson { get; set; } = "[]"; public string? VisualDirection { get; set; } public string? Instruction { get; set; } public bool IsApproved { get; set; } }
public sealed class CreativeVersion { public Guid Id { get; init; } = Guid.NewGuid(); public Guid ContentItemId { get; init; } public int Version { get; init; } public Guid SourceContentRevisionId { get; init; } public required string LayoutJson { get; set; } public string? ImageStorageKey { get; set; } public string? ThumbnailStorageKey { get; set; } public string? RevisionInstruction { get; set; } public bool IsSelected { get; set; } }
