using Microsoft.Extensions.Configuration;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace RedAI.Application;

/// <summary>All live model calls are server-side. Machine-readable stages must use CompleteStructuredAsync.</summary>
public interface IAIClient
{
    string Mode { get; }
    Task<T> CompleteAsync<T>(string operation, object input, CancellationToken cancellationToken = default);
    Task<JsonDocument> CompleteStructuredAsync(StructuredTextRequest request, CancellationToken cancellationToken = default);
    Task<GeneratedImage> GenerateImageAsync(ImageGenerationRequest request, CancellationToken cancellationToken = default);
}

public sealed record StructuredTextRequest(string Operation, string Instructions, object Input, string SchemaName, JsonDocument Schema, string? Model = null);
public sealed record ImageGenerationRequest(string Operation, string Prompt, string Size = "1024x1536", string Quality = "medium", string OutputFormat = "png", string? Model = null);
public sealed record GeneratedImage(byte[] Bytes, string ContentType, string Model);
public sealed record StoredGeneratedImage(StoredAsset Asset, string Model);
public sealed record AIRunStart(string Operation, string EntityType, Guid EntityId, string Model, string InputJson);
public interface IAIRunWriter { Task<Guid> StartAsync(AIRunStart run, CancellationToken ct); Task CompleteAsync(Guid id, string outputJson, CancellationToken ct); Task FailAsync(Guid id, string error, CancellationToken ct); }

public interface IContractSchemaCatalog { JsonDocument Load(string schemaName); }

/// <summary>Loads the frozen schemas in docs/contracts. The root is explicitly configured by the host.</summary>
public sealed class FileContractSchemaCatalog(string contractsRoot) : IContractSchemaCatalog
{
    public JsonDocument Load(string schemaName)
    {
        if (string.IsNullOrWhiteSpace(schemaName) || schemaName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0 || schemaName.Contains("..", StringComparison.Ordinal))
            throw new ArgumentException("Invalid contract schema name.", nameof(schemaName));
        var path = Path.Combine(contractsRoot, schemaName.EndsWith(".schema.json", StringComparison.Ordinal) ? schemaName : $"{schemaName}.schema.json");
        if (!File.Exists(path)) throw new FileNotFoundException($"RED AI contract schema was not found: {schemaName}", path);
        return JsonDocument.Parse(File.ReadAllText(path));
    }
}

/// <summary>Application service that stores generated image bytes under a domain storage key.</summary>
public sealed class VisualAssetGenerator(IAIClient client, IAssetStorage storage)
{
    public async Task<StoredGeneratedImage> GenerateAndStoreAsync(ImageGenerationRequest request, string storageKey, CancellationToken ct = default)
    {
        var generated = await client.GenerateImageAsync(request, ct);
        await using var bytes = new MemoryStream(generated.Bytes, writable: false);
        return new StoredGeneratedImage(await storage.PutAsync(bytes, storageKey, generated.ContentType, ct), generated.Model);
    }
}

public sealed class MockAIClient : IAIClient
{
    public string Mode => "mock";
    public Task<T> CompleteAsync<T>(string operation, object input, CancellationToken cancellationToken = default) => throw new NotSupportedException("Mock outputs are deterministic domain fixtures.");
    public Task<JsonDocument> CompleteStructuredAsync(StructuredTextRequest request, CancellationToken cancellationToken = default) => throw new NotSupportedException("Mock outputs are deterministic domain fixtures.");
    public Task<GeneratedImage> GenerateImageAsync(ImageGenerationRequest request, CancellationToken cancellationToken = default) => throw new NotSupportedException("Mock visual assets are generated by the deterministic renderer.");
}

public sealed class OpenAIResponsesClient(HttpClient http, IConfiguration configuration, IAIRunWriter? runs = null) : IAIClient
{
    public string Mode => "openai";

    public async Task<T> CompleteAsync<T>(string operation, object input, CancellationToken cancellationToken = default)
    {
        using var schema = JsonDocument.Parse("{\"type\":\"object\",\"additionalProperties\":true}");
        using var output = await CompleteStructuredAsync(new StructuredTextRequest(operation, "Return valid JSON.", input, "red_ai_generic", schema), cancellationToken);
        return output.Deserialize<T>() ?? throw new InvalidOperationException("OpenAI returned an empty structured output.");
    }

    public async Task<JsonDocument> CompleteStructuredAsync(StructuredTextRequest request, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(request.Operation); ArgumentException.ThrowIfNullOrWhiteSpace(request.SchemaName);
        var model = request.Model ?? Required("AI:Models:Reasoning");
        var runId = await StartRunAsync(request.Operation, model, request.Input, cancellationToken);
        using var message = Authorized(HttpMethod.Post, "https://api.openai.com/v1/responses");
        // Responses uses text.format/json_schema for strict Structured Outputs.
        message.Content = JsonContent.Create(new {
            model, store = false, instructions = request.Instructions,
            input = JsonSerializer.Serialize(request.Input),
            text = new { format = new { type = "json_schema", name = request.SchemaName, strict = true, schema = JsonNode.Parse(request.Schema.RootElement.GetRawText()) } }
        });
        try { using var response = await http.SendAsync(message, cancellationToken); response.EnsureSuccessStatusCode(); using var body = JsonDocument.Parse(await response.Content.ReadAsStringAsync(cancellationToken)); var json = ExtractOutputText(body.RootElement); await CompleteRunAsync(runId, json, cancellationToken); return JsonDocument.Parse(json); }
        catch (Exception ex) { await FailRunAsync(runId, ex, cancellationToken); throw; }
    }

    public async Task<GeneratedImage> GenerateImageAsync(ImageGenerationRequest request, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(request.Prompt);
        var model = request.Model ?? Required("AI:Models:Image");
        var runId = await StartRunAsync(request.Operation, model, new { request.Prompt, request.Size, request.Quality, request.OutputFormat }, cancellationToken);
        using var message = Authorized(HttpMethod.Post, "https://api.openai.com/v1/images/generations");
        message.Content = JsonContent.Create(new { model, prompt = request.Prompt, size = request.Size, quality = request.Quality, output_format = request.OutputFormat, n = 1 });
        try { using var response = await http.SendAsync(message, cancellationToken); response.EnsureSuccessStatusCode(); using var body = JsonDocument.Parse(await response.Content.ReadAsStringAsync(cancellationToken)); var encoded = body.RootElement.GetProperty("data")[0].GetProperty("b64_json").GetString() ?? throw new InvalidOperationException("OpenAI image response did not contain b64_json."); var type = request.OutputFormat.Equals("jpeg", StringComparison.OrdinalIgnoreCase) ? "image/jpeg" : "image/png"; await CompleteRunAsync(runId, "{\"asset\":\"stored-by-caller\"}", cancellationToken); return new GeneratedImage(Convert.FromBase64String(encoded), type, model); }
        catch (Exception ex) { await FailRunAsync(runId, ex, cancellationToken); throw; }
    }

    private HttpRequestMessage Authorized(HttpMethod method, string uri)
    {
        var message = new HttpRequestMessage(method, uri);
        message.Headers.Authorization = new AuthenticationHeaderValue("Bearer", Required("ai-api-key"));
        return message;
    }
    private string Required(string key) => configuration[key] ?? throw new InvalidOperationException($"Server-side configuration '{key}' is required when AI_MODE=openai.");
    private async Task<Guid?> StartRunAsync(string operation, string model, object input, CancellationToken ct)
    {
        if (runs is null) return null;
        var sanitized = JsonSerializer.Serialize(input).Replace("ai-api-key", "[redacted]", StringComparison.OrdinalIgnoreCase);
        return await runs.StartAsync(new AIRunStart(operation, "ai", Guid.Empty, model, sanitized), ct);
    }
    private Task CompleteRunAsync(Guid? id, string output, CancellationToken ct) => id is { } value && runs is not null ? runs.CompleteAsync(value, output, ct) : Task.CompletedTask;
    private Task FailRunAsync(Guid? id, Exception error, CancellationToken ct) => id is { } value && runs is not null ? runs.FailAsync(value, error.Message, ct) : Task.CompletedTask;
    private static string ExtractOutputText(JsonElement root) => root.GetProperty("output").EnumerateArray()
        .SelectMany(item => item.TryGetProperty("content", out var content) ? content.EnumerateArray() : [])
        .FirstOrDefault(item => item.TryGetProperty("type", out var type) && type.GetString() == "output_text")
        .GetProperty("text").GetString() ?? throw new InvalidOperationException("OpenAI response did not contain output_text.");
}
